### ISSUE TITLE
Padding for short sequences

### ISSUE THREAD

**Issue by jakebeal** [iGEM-Engineering/iGEM-distribution#100]
Twist has a minimum synthesis length that is longer than many promoters and terminators (150 bp, iirc). 
How should we approach padding for short sequences?

**Comment by Sonjabillerbeck** [comment]
One could add standard stretches 5' and 3' that are cleaved during the type II assembly.

**Comment by vinoo-igem** [comment]
I'll reach out to Marc about what Freegenes normally does, we don't have to follow them though. But as an example, they have B0034 here https://freegenes.github.io/genes/BBF10K_003410.html where they have a 43 bp insert with 400bp additionally synthesized (60 of which is for their barcode)

I made some quick additions and deletions to their annotations, to show the extra bases that they added. Not great ones, just to be quick https://benchling.com/s/seq-b8FOT2bE7kCrp4z7pCeY.

**Comment by GC-repeat** [comment]
Should the padding sequences adjusted the minimum length requirement so we're not paying for extra unused bases what could represent a substantial price on the volume ? I would probably not go to an adjustment by the base but rather with couple sets of padding sequences with intermediate length that we know get synthesized nicely.

**Comment by vinoo-igem** [comment]
Closing this as #213 and #231 exist
