### ISSUE TITLE
Validate Part sequence vs Part in Backbone sequence

### ISSUE THREAD

**Issue by vinoo-igem** [iGEM-Engineering/iGEM-distribution#137]
Before we proceed with our first order, we need to verify that the part sequence in any package is correctly represented in the following:
https://github.com/iGEM-Engineering/iGEM-distribution/blob/develop/distribution_synthesis_inserts.fasta

And that part sequence* is correctly in the Part in Backbone sequence as documented here
https://github.com/iGEM-Engineering/iGEM-distribution/blob/develop/distribution.gb

This assumes that we have correctly specified and added any flanking sequences between these steps. I'll link to that issue here.

We also need to document our validation process so that it can be automated.

**Comment by vinoo-igem** [comment]
I've started checking the Part sequence vs the Part Insert vs Part in Backbone for the Interlab Devices. I'll followup with my methods

But, in this case we have... 

1. the Part = An Interlab construct, as specified on the Registry
2. the Part Insert = The Interlab construct with 0bp of flanking added
3. the Plasmid Backbone = pSB1C3 (Specified exactly within Twist)
4. the Part in Plasmid Backbone = the Part Insert in the Plasmid Backbone

Notably, this is a much easier check because the Part = Part Insert in this case. But, how do we want to specify the flanking sites for Parts, so that the Part Insert is exactly as specified. On the build sheet? @jakebeal

**Comment by vinoo-igem** [comment]
For checks, I aligned Registry sequences of the Part and Plasmid Backbone against the following and manually checked for...

[Part Insert](https://github.com/iGEM-Engineering/iGEM-distribution/blob/develop/distribution_synthesis_inserts.fasta)
- 5' flanking
- part
- 3' flanking

[Part in Backbone](https://github.com/iGEM-Engineering/iGEM-distribution/blob/develop/distribution.gb)
- part insert (above)
- plasmid backbone

**Comment by noahsprent** [comment]
@vinoo-igem When you say "document our validation process so that it can be automated" do you mean that we need a page in the documentation that will describe this, or just that you want to describe what you do here well enough that it can be automated? I'm trying to clean up the 'documentation' tag.

**Comment by noahsprent** [comment]
@vinoo-igem Do we need to add a page to the documentation where we describe our validation process? If so, shall we open a new issue and close this one, or clarify this one?

**Comment by vinoo-igem** [comment]
@noahsprent I believe the original intent was to have internal documentation to point out what we will need automated in the future. Thinking about it though, a page on the validation process as a whole would be useful, and should be a new issue #315.
