### ISSUE TITLE
Naming scheme for Interlab Constructs/Challenges

### ISSUE THREAD

**Issue by GC-repeat** [iGEM-Engineering/iGEM-distribution#144]
Find a name/naming scheme for each of the Interlab study so we can more easily know which one we're talking about. 

A first suggestion is Interlab_XX_Year where XX is the type of experiment or question being asked.

**Comment by GC-repeat** [comment]
For sorting consideration, if we go for something like Interlab_XX_Year maybe Interlab_Year_XX would work better ?

**Comment by jakebeal** [comment]
My tendency would be to go Interlab_Year_XX so that they will sort well together.

**Comment by vignoni** [comment]
@Sonjabillerbeck and I are discussing this.

**Comment by vignoni** [comment]
Proposal:

Interlab_Year_XX

XX being:
Plate_reader2018
Three_colours
Double_constructs

**Comment by GC-repeat** [comment]
I would go for camelCase for the XX part so it's easier to see the 3 components. So XX would be:
- PlateReader2018
- ThreeColors
- DoubleConstructs
