### ISSUE TITLE
Set up a documentation site

### ISSUE THREAD

**Issue by noahsprent** [iGEM-Engineering/iGEM-distribution#155]
With more people, and eventually teams, getting involved, I think it might be nice to expand the documentation beyond READMEs. [Read the docs](https://readthedocs.org/) is a very common way of doing this, at least for Python packages, so I suggest we start there, with sphynx to build the documentation.

![image](https://user-images.githubusercontent.com/39567418/149905665-47466305-a1f6-4bfb-b729-1115078d57a8.png)

**Comment by noahsprent** [comment]
I've opened the pull request #156 to get a minimal read the docs site setup

**Comment by GC-repeat** [comment]
Documentation on how to contribute packages to the distribution. The "safe/newbie" way : fork, branch, pull request and the "you know what you're doing" way : branch, pull request.

**Comment by noahsprent** [comment]
For an idea of what a read-the-docs site can look like: https://docs.readthedocs.io/en/stable/

**Comment by noahsprent** [comment]
Docs are here, just waiting on someone with permissions to enable git hooks so it will autoupdate: https://igem-distribution.readthedocs.io/en/latest/
