### ISSUE TITLE
FASTA imports need type from Excel sheet

### ISSUE THREAD

**Issue by jakebeal** [iGEM-Engineering/iGEM-distribution#168]
FASTA imports have no type information, so they need to get it from the Excel sheet. This isn't currently happening, however.

Example of the issue: pSB1C5 in https://github.com/iGEM-Engineering/iGEM-distribution/pull/150#issuecomment-1018831757

**Comment by jakebeal** [comment]
This is a sub-issue of #131

**Comment by ethanj801** [comment]
Was going to open an issue for this, same problem happens in the small molecule inducers package.

**Comment by jakebeal** [comment]
A fix for the special case of missing/generic role information is pending in #171
That will solve the problem of missing type (actually role) information for all import formats, including FASTA,
