### ISSUE TITLE
Add 'what the heck is the distribution 2.0' section/page to the docs

### ISSUE THREAD

**Issue by noahsprent** [iGEM-Engineering/iGEM-distribution#178]
I think it would be useful for people who just find the repo without having been properly introduced to the project to have a page in the docs that introduces the philosophy etc. A bit of a 'meta' page.

**Comment by noahsprent** [comment]
Perhaps one for @vinoo-igem to write at some point?

**Comment by noahsprent** [comment]
Question on slack that could be answered on this page: How many parts will be included in the Distro v2.0? similar to the past Distributions, around 6 384-well plates, more, less? And an extension of this question, do we have limitations on part number per collection?

**Comment by vinoo-igem** [comment]
I'm going to continue working on this this week (sporadically!) including @noahsprent and @plouisross suggestions, along with other documentation bits.

**Comment by noahsprent** [comment]
Great, thanks @vinoo-igem! If you are going to work on any other pages/bits please make sure to assign yourself to the issue and move it to 'in-progress' on the Kanban board so we know what everyone is doing. https://github.com/orgs/iGEM-Engineering/projects/1

**Comment by noahsprent** [comment]
@vinoo-igem Did I imagine this or is there a more up-to-date version now? If there isn't we should close this issue.

**Comment by vinoo-igem** [comment]
@noahsprent yea, it can use some updating but should be closed as there is not an update version ready to go.
