### ISSUE TITLE
Decision on assembly standard for part samples

### ISSUE THREAD

**Issue by vinoo-igem** [iGEM-Engineering/iGEM-distribution#18]

**Comment by vignoni** [comment]
Compatibility either with Type IIS or Type II, or even with both at the same time.
Presumably for basic parts assembly into a composite/transcriptional unit  (Level 0->Level 1) can be Type IIS and the Level 1 manipulation can have both types of assemblies.

**Comment by vinoo-igem** [comment]
closing as this has been decided as Type IIS and will be formalized #137, #141 and #165
