### ISSUE TITLE
rdflib-jsonId dependency warning

### ISSUE THREAD

**Issue by nickdelkis** [iGEM-Engineering/iGEM-distribution#209]
The following warning appears in different scripts when starting up. Do we need to take action?

> /opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/rdflib_jsonld/__init__.py:9: DeprecationWarning: The rdflib-jsonld package has been integrated into rdflib as of rdflib==6.0.1.  Please remove rdflib-jsonld from your project's dependencies.

**Comment by jakebeal** [comment]
I've been noticing it too, and haven't figured out where it's coming from, since rdflib is included only indirectly. It doesn't seem to be breaking anything, but it would be good for somebody to track it down and figure out which dependency it's coming through, so that can be fixed upstream.

**Comment by jakebeal** [comment]
Found it on sbol_factory, and am attempting to fix over there: https://github.com/SynBioDex/sbol_factory/issues/67

**Comment by jakebeal** [comment]
The sbol_factory fix is in, so this issue should resolve as soon as the next sbol_factory release is made.

**Comment by noahsprent** [comment]
@jakebeal Just following up, has this been resolved?

**Comment by jakebeal** [comment]
I believe so: there has certainly been an sbol_factory release since this.
