### ISSUE TITLE
Naming/id conventions of constructs for synthesis runs at TWIST

### ISSUE THREAD

**Issue by vinoo-igem** [iGEM-Engineering/iGEM-distribution#210]
I've run into a known issue where TWIST accepts names of 32 chars. This does not need to be fixed now, but needs to be addressed in the future with some agreement with FreeGenes over the way this is handled so that they can know exactly what they are getting.
Simplest solution, unique IDs attached to the human readable description and sub-components in full (eventually for an area for BBa_ as well).

**Comment by jakebeal** [comment]
Note that solving by #83 and #SynBioDex/SBOL-utilities/issues/104 will go a long way toward resolving this.
