### ISSUE TITLE
Create tetR ortholog collection

### ISSUE THREAD

**Issue by vinoo-igem** [iGEM-Engineering/iGEM-distribution#22]

**Comment by traci-igem** [comment]
I'll be adding the TetR ortholog library from the [2014 Voigt paper "Genomic Mining of Prokaryotic Repressors for Orthogonal Logic Gates"] (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4165527/). This will allow teams / users to build more complex, orthogonal genetic devices and will expand the repressor toolkit in the Distribution Kit. This will include 19 new repressor - promoter pairs.

**Comment by jakebeal** [comment]
There's a Cello parts collection you might want to pull with updated versions of these: https://synbiohub.programmingbiology.org/public/Cello_Parts/Cello_Parts_collection/1

These are the materials from: Nielsen, AA., Der, BS., Shin, J., Vaidyanathan, P., Paralanov, V., Strychalski, EA., Ross, D., Densmore, D., Voigt, CA., "Genetic circuit design automation.", Science (New York, N.Y.), 2016, Apr 01; 352(6281): aac7341, PMID: 27034378., DOI: 10.1126/science.aac7341.

**Comment by traci-igem** [comment]
For the SynBioHub, is there an automated process in place to pull the sequence information for the parts listed in the Excel file?

**Comment by jakebeal** [comment]
Not yet, but I can add one --- there's already automation for getting iGEM parts from SynBioHub, so I just need to add handling for another line on the data source table.

For now, just add the synbiohub URI in the "Data Source ID" column

**Comment by traci-igem** [comment]
I'm looking at SynBioHub now and I'm not sure what you mean by "SynBioHub URI" - or was that URL with a lower case "L"? If it's the URL, then for the example below, which URL should I copy into the Excel file? 
The general info page (top) or the sequence page (bottom):
[AmtR](https://synbiohub.programmingbiology.org/public/Cello_Parts/AmtR/1)
or
[AmtR Sequence](https://synbiohub.programmingbiology.org/public/Cello_Parts/AmtR_sequence/1)

**Comment by jakebeal** [comment]
Apologies for the confusion: "URI" is a generalization of "URL" that includes things that don't start with "http" :-)

What you should put in is the URL for AmtR, as that will also collect the any sub-parts and the sequence along with it.
