### ISSUE TITLE
Duplicates in CRISPR Cas collection

### ISSUE THREAD

**Issue by vinoo-igem** [iGEM-Engineering/iGEM-distribution#234]
I did a quick check of the distro fasta through TWIST, and they found some duplicates

Anti_CRISPR_AcrIIA2_bacterial
Anti_CRISPR_AcrIIA4_bacterial
Anti_CRISPR_AcrIIA4_mammalian

I think somewhere along the way the .gb files for these were either confused, as they all have the correct locus name, but their .gb files reveals that their CDS label annotation is AcrIIA2_bacterial for all three of them.

If someone can make a pull request to fix these by tomorrow morning great! If not, I'll remove them and we can add these to the next run.

**Comment by nickdelkis** [comment]
Ah, my bad when exporting .gb files. Will fix for next batch!
