### ISSUE TITLE
Link to readthedocs

### ISSUE THREAD

**Issue by jakebeal** [iGEM-Engineering/iGEM-distribution#245]
We should have a link to https://igem-distribution.readthedocs.io right at the top of the README, and most of the current README content should moved over there and deleted.

**Comment by Aman-Mandal** [comment]
Can you assign me this issue?

**Comment by noahsprent** [comment]
We still need to move the README content over, but #247 at least adds the link.

**Comment by noahsprent** [comment]
I think the link could also go in the 'About' of the repository @vinoo-igem?

**Comment by noahsprent** [comment]
@vinoo-igem Please could you add the link to read-the-docs in the 'website' section of the repo? (Instructions [here](https://stackoverflow.com/questions/7757751/how-do-you-change-a-repository-description-on-github)) Then I think we can close this. Unless you think a better website would be on igem.org? Alternatively we can include a link to a page on igem.org right at the top of the RTD site.

**Comment by vinoo-igem** [comment]
@noahsprent added to the about section! Looks like the separate website section in the stackoverflow instructions is now deprecated.
