### ISSUE TITLE
Should we include docs/_build files in the repository?

### ISSUE THREAD

**Issue by noahsprent** [iGEM-Engineering/iGEM-distribution#307]
The docs/_build folder is what sphinx creates from the raw docs files upon running `make html`, it contains the .html files etc. for the documentation site.

We can:

1. Add docs/_build files to the repository, and include an action to build docs when committing, so that people have the docs ready-built for local and github viewing
2. Add docs/_build to the .gitignore so that they aren't included in version control when they are built locally

Some discussion here: https://stackoverflow.com/questions/9570382/which-files-should-i-tell-my-vcs-to-ignore-when-using-sphinx-for-documentation.

I think my preference would be to add it to the .gitignore, as RTD already builds and hosts the docs for us and if you're using the docs locally you probably know how to build them.

**Comment by jakebeal** [comment]
I agree that it should not be added to the repository.

**Comment by noahsprent** [comment]
My bad, I'd already done this in #254, I was checked out of main instead of develop.
