### ISSUE TITLE
Package stats

### ISSUE THREAD

**Issue by jakebeal** [iGEM-Engineering/iGEM-distribution#39]
For each package, we should be able to collect and record stats for its contents, including:
- number of unique parts
- classes of parts
- number of plasmids used
- number of parts per organism
- number of part/backbone combinations (i.e., wells required)
- types of organisms targeted by the package
- issues in the package

Put all of this into an automatically generated README file for the package

We should also do this for the top-level "complete distribution package", which will necessarily have duplicates that get unioned.

**Comment by jakebeal** [comment]
This should also include a list of the unused parts in the directory, though that will require some resolution of #75

**Comment by jakebeal** [comment]
Remove this from end-to-end automation because #76 provides a sufficient amount for the initial end-to-end enablement of orders, but there's more to be done in this issue.

**Comment by jakebeal** [comment]
#101 addresses everything at the package level except for organism information, which we'll consider later.

**Comment by noahsprent** [comment]
@jakebeal Would it be reasonable to split this into two separate issues. One for generating a summary of organism information at the package level, and a second for generating this summary for the whole distribution? I see that there is at least 'n samples planned for distribution' at the whole-distribution level currently.

**Comment by jakebeal** [comment]
I believe the package level is complete, so we should probably just have a new issue for the whole-distribution level, so it's less confusing what needs to be done.

**Comment by noahsprent** [comment]
Ok, I've created that issue: #320
