### ISSUE TITLE
Clarify that Library & Composite = Build

### ISSUE THREAD

**Issue by jakebeal** [iGEM-Engineering/iGEM-distribution#4]
Need to clarify the purpose of the library & composite spreadsheet in the README, explaining that it's how we do the build planning.  Point to the anderson library example as an example.
Also explain the "final product" column

**Comment by vinoo-igem** [comment]
Related to this, is clarification for the use of "basic" parts since we will also be entering composite parts (ex. J04450) to preserve the way they were assembled (exact sequence) and their documentation/previous

**Comment by vignoni** [comment]
This is related to an issue that we also have with @jakebeal and Rene I. in the 3rd order. 
Don't we want to make the composite parts from basic parts (even if we want to add the composite one)?
I am in favor to preserve the sequence and I think doing it this way is a good way. 
Also useful for integrity check and validation, as you can validate a composite part by checking its constituent connections.
