### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by jakebeal** [iGEM-Engineering/iGEM-distribution#42]
We need to put license terms on this repository to regulate the contributions.
I would suggest that the distribution be https://creativecommons.org/licenses/by/4.0/, which I believe is the same that is used for the registry, and the scripting code use the MIT license.

This should be declared in a LICENSE.txt file at the root directory.

**Comment by vinoo-igem** [comment]
Yup, the CC license is correct. As far as I'm aware we haven't required a specific license for code, but I the MIT license seems most appropriate.

**Comment by jakebeal** [comment]
Great; whichever of us gets to it first can set up the documents then.

**Comment by vinoo-igem** [comment]
Happy to get that done by tomorrow. Would copyright fall under BBN, iGEM, BBN and iGEM, or individuals (You)?
