### ISSUE TITLE
Small molecule inducers need CDS sequences

### ISSUE THREAD

**Issue by jakebeal** [iGEM-Engineering/iGEM-distribution#52]
The Small Molecule Inducers package is currently missing CDS sequences for TetR and AraC. We should identify parts in the iGEM repository to use for these.

**Comment by traci-igem** [comment]
TetR is BBa_C0040

**Comment by jakebeal** [comment]
Want to grab this issue and put in the fix on the package? Should be a good first exercise for contributing material.
