### ISSUE TITLE
Additional small-molecule inducers?

### ISSUE THREAD

**Issue by jakebeal** [iGEM-Engineering/iGEM-distribution#53]
The Small Molecule Inducer package supports three small molecules at present, arabinose, tetracycline, and IPTG. Are there any others that we should add?

**Comment by JMejlsted** [comment]
It might be interesting to add some of the Marionette promoters to allow for more inputs. All 12 promoters are probably overkill, but a couple could be very useful for teams. 
So far, I have found the vanillic acid promoter ([K3317006](http://parts.igem.org/wiki/index.php/Part:BBa_K3317006)) and its regulator ([K3317004](http://parts.igem.org/Part:BBa_K3317004)) in the iGEM registry

**Comment by jakebeal** [comment]
Sounds like an excellent idea!  Want to grab all of the ones that appear in the registry and set up a pull request?

**Comment by JMejlsted** [comment]
I will try to find as many parts as I can in the registry. I might need a hand with GitHub, as I am not too familiar with the system yet.

**Comment by jakebeal** [comment]
Happy to help as needed; I recommend starting with the slides I shared on Monday.
