### ISSUE TITLE
Structure: Parts, functional unit, sequence, and assembly

### ISSUE THREAD

**Issue by vinoo-igem** [iGEM-Engineering/iGEM-distribution#59]
This is a much larger discussion that came up today, so @jakebeal please correct me if I may be misremembering or missing some scope. 
Currently we are operating under the iGEM Registry's practice that a Registry part does not include aspects of the assembly method: a part/functional unit in Biobrick format vs Type IIS is the exact same, and that the plasmid backbone (really the sample of that part) will dictate assembly.
But parts can operate differently based on their assembly method (the exact sequence, or the amount of bases, flanking them within a device). 
Should a part and its associated documentation reflect its assembly: should they contain the bases flanking the functional unit when it is "cut out"?
What are everyone's recommended structure, and terminology that we should be using to talk about these?

**Comment by jakebeal** [comment]
I believe that I just opened the same issue as #58 :-)

**Comment by vinoo-igem** [comment]
Yup I just saw that! That's what I get for having a draft open, I'll delete this.

**Comment by jakebeal** [comment]
Duplicate are better than missing information!
